use_frameworks!

target 'ZWSGetLaunchView_Example' do
  pod 'ZWSGetLaunchView', :path => '../'

  target 'ZWSGetLaunchView_Tests' do
  pod 'ZWSGetLaunchView', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
